### ISSUE TITLE
[BUG]: B3_20220715 point cloud without colour data

### ISSUE THREAD

**Issue by gcielniak** [KarolineH/projectpage#5]
### Description of the bug

The only point cloud without colour data. Is this recoverable or gone forever?

### Steps To Reproduce

See the NextCloud folder.

**Comment by KarolineH** [comment]
This one sadly had no colour information recorded from the start so all of our backups at various stages of this sample have no original colour.

**Comment by gcielniak** [comment]
The colour data was recovered from the scanning laptop. Success!
