### ISSUE TITLE
[BUG]: Distant point removal and alignment fix

### ISSUE THREAD

**Issue by gcielniak** [KarolineH/projectpage#6]
### Description of the bug

These are small fixes that standardise the dataset:
- Distant points removed: A1_20220525, A2_20220531, A2_20220623
- Alignment fixed: B2_20220620

Files added to NextCloud with the `_fix` suffix and once approved by @KarolineH and @KatherineJames can be renamed and then overwrite the originals. 

### Steps To Reproduce

See the NextCloud folder.

**Comment by KarolineH** [comment]
All changes reviewed, accepted, and updated on Nextcloud.
